version: '3.7'

volumes:
  certs:
  nginx_conf:
  nginx_dhparam:
  nginx_html:
  nginx_vhost:

networks:
  frontend:

services:
  app_server:
    image: tec27/seatcamp:latest
    restart: unless-stopped
    # Required for proper handling of kernel signals (eg. ctrl-c); for more info, see:
    # https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals
    init: true
    environment:
      # This controls what addresses nginx_proxy will forward to this
      - VIRTUAL_HOST=${SEATCAMP_VIRTUAL_HOST}
      - VIRTUAL_PORT=5555
      - LETSENCRYPT_HOST=${SEATCAMP_VIRTUAL_HOST}
      - SEATCAMP_PORT=5555
      - SEATCAMP_ID_KEY=${SEATCAMP_ID_KEY:?missing SEATCAMP_ID_KEY}
      - SEATCAMP_GA_ID=${SEATCAMP_GA_ID}
      - SEATCAMP_CANONICAL_HOST=${SEATCAMP_CANONICAL_HOST}
      - SEATCAMP_TRUST_PROXY=1
    networks:
      - frontend
    depends_on:
      - nginx_proxy
      - proxy_gen

  nginx_proxy:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    volumes:
      - certs:/etc/nginx/certs:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
    networks:
      - frontend

  # This generates reverse proxy configurations for nginx, setup taken from:
  # https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Docker-Compose.md
  # (the three container setup)
  proxy_gen:
    image: jwilder/docker-gen:0.7.6
    restart: unless-stopped
    command: -notify-sighup nginx_proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    environment:
      - ENABLE_IPV6=true
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'
    volumes:
      - certs:/etc/nginx/certs:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - ./docker-nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
    depends_on:
      - nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=${SEATCAMP_LETSENCRYPT_EMAIL}
    volumes:
      - certs:/etc/nginx/certs:rw
      - nginx_html:/usr/share/nginx/html
      - nginx_vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    depends_on:
      - nginx_proxy
      - proxy_gen

